### PR TITLE
[FIX] copy method in account/models/account_tax.py overrides the defa…

### PR DESCRIPTION
**Pull request by b-kannan**
…ult dict passed and resets name. So, setting the name explicitly in the connector module.

### CODE REVIEW

**Comment by b-kannan** [comment]
@bodedra @dreispt Please push upstream and merge to OCA after merge here. Thanks

**Comment by bodedra** [comment]
@b-kannan would you please remove module version changes. It will be managed by OCA bot.

Also squash commit in 1 and I will take care of upstream.

PR LGTM :+1: 

Thank you.

**Comment by b-kannan** [comment]
@bodedra : Reverted the revision number

**Comment by dreispt** [comment]
PRs should be created at OCA/account-fisca-rule. https://github.com/OCA/account-fiscal-rule
Thanks!

**Comment by b-kannan** [comment]
@bodedra Squashed and merged locally. Please move changes to OCA as mentioned by @dreispt. Thanks

**Comment by dreispt** [comment]
Make sure you deploy using a customer specific branch.
There is a risk that this 14.0 branch is reset to OCA/14.0 at any time.

**Pull request merged**
